CREATE TABLE IF NOT EXISTS subjects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, color text NOT NULL DEFAULT 'green');
CREATE TABLE IF NOT EXISTS topics(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_id uuid NOT NULL REFERENCES subjects, name text NOT NULL, UNIQUE(subject_id,name), UNIQUE(id,subject_id));
CREATE TABLE IF NOT EXISTS tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, subject_id uuid NOT NULL REFERENCES subjects, topic_id uuid, estimated double precision NOT NULL CHECK(estimated>0 AND estimated<=1440),remaining double precision NOT NULL CHECK(remaining>=0 AND remaining<=1440),status text NOT NULL DEFAULT 'TODO' CHECK(status IN ('TODO','IN_PROGRESS','COMPLETED','CANCELLED')),note text NOT NULL DEFAULT '',is_review boolean NOT NULL DEFAULT true,bucket text NOT NULL CHECK(bucket IN ('ENGLISH','FLEXIBLE')),routine_date date UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(topic_id,subject_id) REFERENCES topics(id,subject_id));
CREATE TABLE IF NOT EXISTS plans(task_id uuid PRIMARY KEY REFERENCES tasks ON DELETE CASCADE,level text NOT NULL CHECK(level IN ('UNSCHEDULED','MONTH','WEEK','DAY','FIXED')),on_date date,fixed_time text,CHECK((level='UNSCHEDULED' AND on_date IS NULL AND fixed_time IS NULL) OR (level IN ('MONTH','WEEK','DAY') AND on_date IS NOT NULL AND fixed_time IS NULL) OR (level='FIXED' AND on_date IS NOT NULL AND fixed_time IS NOT NULL)));
CREATE TABLE IF NOT EXISTS subtasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id uuid NOT NULL REFERENCES tasks ON DELETE CASCADE,title text NOT NULL,completed boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id uuid NOT NULL REFERENCES tasks,state text NOT NULL CHECK(state IN ('RUNNING','PAUSED','STOPPED','COMPLETED')),started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_session ON sessions((true)) WHERE state IN ('RUNNING','PAUSED');
CREATE TABLE IF NOT EXISTS intervals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES sessions,start_at timestamptz NOT NULL,end_at timestamptz,CHECK(end_at IS NULL OR end_at>=start_at));
CREATE UNIQUE INDEX IF NOT EXISTS one_live_interval ON intervals(session_id) WHERE end_at IS NULL;
CREATE TABLE IF NOT EXISTS reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),subject_id uuid NOT NULL REFERENCES subjects,topic_id uuid,session_id uuid UNIQUE REFERENCES sessions,reviewed_at timestamptz NOT NULL,duration double precision CHECK(duration>=0),source text NOT NULL CHECK(source IN ('SESSION','MANUAL')),note text NOT NULL DEFAULT '',FOREIGN KEY(topic_id,subject_id) REFERENCES topics(id,subject_id));
CREATE TABLE IF NOT EXISTS settings(id integer PRIMARY KEY CHECK(id=1),routine jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS reminders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id uuid NOT NULL UNIQUE REFERENCES tasks ON DELETE CASCADE,due_at timestamptz NOT NULL,delivered_at timestamptz,error text);
CREATE TABLE IF NOT EXISTS push_subscriptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),endpoint text NOT NULL UNIQUE,subscription jsonb NOT NULL);
INSERT INTO subjects(name,color) VALUES ('English','green'),('Chinese','blue'),('Biology','ochre'),('DT','purple') ON CONFLICT DO NOTHING;
INSERT INTO topics(subject_id,name) SELECT id,'Writing' FROM subjects WHERE name IN ('English','Chinese') ON CONFLICT DO NOTHING;
INSERT INTO topics(subject_id,name) SELECT id,'Classical Chinese' FROM subjects WHERE name='Chinese' ON CONFLICT DO NOTHING;
INSERT INTO settings VALUES(1,'{"days":[{"english":0,"flexible":240,"start":"10:00"},{"english":120,"flexible":120,"start":"18:00"},{"english":120,"flexible":120,"start":"18:00"},{"english":120,"flexible":120,"start":"18:00"},{"english":120,"flexible":120,"start":"18:00"},{"english":120,"flexible":120,"start":"18:00"},{"english":0,"flexible":240,"start":"10:00"}]}') ON CONFLICT DO NOTHING;

ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS position bigserial;
